name: odimra_deploy

on:
  pull_request:
    branches:
      - '**'

jobs:

  build:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: configure pre-req for odimra deployment
      run: |
        echo "Start pre req conguration"
        pwd
        ls -ltr
        sudo apt update
        sudo apt-get install sshpass -y
        sudo apt-get install python3.8 -y
        sudo apt install python3-pip -y
        python3 --version
        echo "python version"
        sudo apt install software-properties-common -y
        sudo -E apt-add-repository ppa:ansible/ansible
        sudo apt install openjdk-8-jre-headless -y
        sudo apt-get install python3-setuptools
        python3 -m pip install --upgrade pip
        pip3 install pyyaml==5.3.1
        pip3 install pycryptodomex==3.9.7
        cp kube_deploy_nodes.yaml.tmpl kube_deploy_nodes.yaml
        cat kube_deploy_nodes.yaml



